ignore:
  - "Com.Efrata.Service.Purchasing.Lib/Migrations" 
  - "Com.Efrata.Service.Purchasing.Lib/AutoMapperProfiles" 
  - "Com.Efrata.Service.Purchasing.Lib/Serializers" 
  - "Com.Efrata.Service.Purchasing.Lib/Services" 
  - "Com.Efrata.Service.Purchasing.Lib/Facades/BudgetCashflowService" 
  - "Com.Efrata.Service.Purchasing.Lib/Facades/DebtAndDispositionSummary" 
  - "Com.Efrata.Service.Purchasing.Lib/Facades/DebtAndDispositionSummary" 
  - "Com.Efrata.Service.Purchasing.Lib/Facades/GarmentPurchasingExpedition" 
  - "Com.Efrata.Service.Purchasing.Lib/Facades/GarmentBeaCukaiFacade" 
  - "Com.Efrata.Service.Purchasing.Lib/Facades/GarmentDailyPurchasingReportFacades" 
  - "Com.Efrata.Service.Purchasing.Lib/Facades/GarmentDispositionPurchaseFacades" 
  - "Com.Efrata.Service.Purchasing.Lib/Facades/GarmentInternNoteFacades" 
  - "Com.Efrata.Service.Purchasing.Lib/Facades/GarmentInvoiceFacades" 
  - "Com.Efrata.Service.Purchasing.Lib/Facades/MonitoringCentrallBillExpenditureFacades" 
  - "Com.Efrata.Service.Purchasing.Lib/Facades/MonitoringCentrallBillReceptionFacades" 
  - "Com.Efrata.Service.Purchasing.Lib/Facades/MonitoringCorrectionNoteExpenditureFacades" 
  - "Com.Efrata.Service.Purchasing.Lib/Facades/MonitoringCorrcetionNoteReceptionFacades" 
  - "Com.Efrata.Service.Purchasing.Lib/Facades/PurchaseRequestFacades" 
  - "Com.Efrata.Service.Purchasing.Lib/Facades/UnpaidDispositionReportFacades" 
  - "Com.Efrata.Service.Purchasing.Lib/MongoDbContext.cs" 
  - "Com.Efrata.Service.Purchasing.WebApi/Startup.cs"
  - "Com.Efrata.Service.Purchasing.WebApi/Program.cs"
  - "Com.Efrata.Service.Purchasing.WebApi/Tools"
  - "Com.Efrata.Service.Purchasing.WebApi/Controllers/v1/ExternalPurchaseOrderControllers"
  - "Com.Efrata.Service.Purchasing.WebApi/Controllers/v1/InternalPurchaseOrderControllers"
  - "Com.Efrata.Service.Purchasing.WebApi/Controllers/v1/PurchaseRequestControllers"
  - "Com.Efrata.Service.Purchasing.WebApi/Controllers/v1/BudgetCashflowController.cs"
  - "Com.Efrata.Service.Purchasing.WebApi/Controllers/v1/GarmentBeaCukaiControllers"
  - "Com.Efrata.Service.Purchasing.WebApi/Controllers/v1/GarmentInvoiceControllers"
  - "Com.Efrata.Service.Purchasing.WebApi/Controllers/v1/GarmentPurchasingExpeditionController.cs"
  - "Com.Efrata.Service.Purchasing.WebApi/Controllers/v1/UnpaidDispositionReport"
  - "Com.Efrata.Service.Purchasing.WebApi/SchedulerJobs/MasterRegistry.cs"
